# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mgmt-agent.resourceNamePrefix" . }}-metrics
  namespace: {{ include "mgmt-agent.namespace" . }}
data:
  monitoring.properties: |
    # compartmentId to push Monitoring metrics
    compartmentId={{ .Values.kubernetesCluster.compartmentId }}
    # Kubernetes cluster name
    clusterName={{ include "mgmt-agent.kubernetesClusterName" . }}
    # Kubernetes Namespace to monitor
    kubernetesNamespace={{ .Values.kubernetesCluster.namespace }}
